name: federate

on:
  workflow_dispatch:
  push:
    branches:
    - '*'
jobs:
  auth:
    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'
    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Install faas-cli
        run: curl -sLS https://cli.openfaas.com | sudo sh
      - uses: self-actuated/openfaas-oidc@master
        with:
          gateway: https://of-proxy.welteki.dev

      - name: Get token and use the CLI
        run: |
          export OPENFAAS_URL=https://of-proxy.welteki.dev
          faas-cli store deploy env --name http-header-printer
          faas-cli list
